#!/usr/bin/env python
# this script allows me to calculate equations 1 and 2 from Romiguier et al 2010
'''
inputs are:
   directory containing gc.trees and .lk files generated by nhphyml
   relationship between each node and the parent node - I did this by hand importing a gc.tree into figtree and then creating a csv file by pairing nodes with parents
   I also need to specify the name and directory where I want the two output json files to be (dij_outupt and dianc_output)
'''

import re
import os
import pandas as pd
import math
import statistics
import json
import subprocess

class TreeParser:
    def __init__(self):
        # this holds the node:gc_content info that is given in the  .tree and .lk files, it is reset for each ortholog
        self.node_gc_dict = {}
        self.node_counter = 44  # Start node number at 44; used for assigning node numbers after taxon tips
        self.end_ij = '.phylip_nhPhymlGC.tree'
        self.end_ancestral = '.phylip_nhPhyml.lk'
        self.end_phylip = '.phylip'
        # this will need to be a list that contains all the newick file names. - something like os.listdir() for the path of all the phylip_nhPhymlGC.tree files
        self.output_path = '/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/genomes_2/busco_run_05_results/02_consolidate_copy/02_with_names' # this is the path where the nhPhyml output is kept
        # this ortholog list will be used to ensure that ancestral and estimated gc content are pulled from files corresponding to the same ortholog
        self.ortholog_list = [file[:-7] for file in os.listdir(self.output_path) if file.endswith(self.end_phylip)]
        # this is a list of GC tree files
        self.newick_list = [file for file in os.listdir(self.output_path) if file.endswith(self.end_ij)]
        # this is a list of files containing the ancestral value
        self.ancestral_list = [file for file in os.listdir(self.output_path) if file.endswith(self.end_ancestral)]
        # this is a csv that contains the node-to-parent relationship that I outlined by hand. This csv needs to be created before running this script
        self.node_details = '/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/genomes_2/busco_run_05_results/dij_gecko_rooted.csv' 
        self.node_relationship = {} # for each node (which is a key in this dictionary) there will be a list that will hold the difference between i and j
        self.node_anc_relationship = {} # for each species (which is a key in this dicitonary) there will be a list that contains the squared difference between the species GC3 and the 
        self.node_gc3_total = {}
        self.relationship_sum = []
        # this will be the ortholog that is currently being analyzed
        self.newick_string = None
        self.ancestral_string = None
        # this will hold the final distance between each node i,j
        self.dij_dict = {}
        # this will hold the final dianc for each species
        self.dianc_dict= {}
        self.number_of_orthologs = len(self.ortholog_list)
        # this needs to be edited to the directory and filename I want to output
        self.dij_output = '/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/projects_local/projects/genomes/records/compleasm/alignments/t1.0_e1_o26_with_s_punctatus/08_final_outputs/dij_results_20260427.json'
        self.dianc_output= '/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/projects_local/projects/genomes/records/compleasm/alignments/t1.0_e1_o26_with_s_punctatus/08_final_outputs/dianc_results_20260427.json'
        self.gc3_output = '/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/projects_local/projects/genomes/records/compleasm/alignments/t1.0_e1_o26_with_s_punctatus/08_final_outputs/gc3_results_20260427.json'
        self.gc3_vs_stdv_output =  '/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/projects_local/projects/genomes/records/compleasm/alignments/t1.0_e1_o26_with_s_punctatus/08_final_outputs/gc3_vs_stdv_20260427'+str(self.number_of_orthologs)+'.csv'
        self.top = '/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/projects_local/projects/genomes/records/compleasm/alignments/t1.0_e1_o26_with_s_punctatus/08_final_outputs/'
        self.dir_gc3_per_gene = '/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/projects_local/projects/genomes/records/compleasm/alignments/t1.0_e1_o26_with_s_punctatus/08_final_outputs/03_gc3_per_gene'
        self.genome_size_csv = '/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/old/genomes_2/genomes/trash/old/genome_size.csv'
        self.species_mass_csv = '/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/old/genomes_2/busco_run_05_results/species_mass.csv' 
        self.species_common_csv = '/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/genomes_2/busco_run_05_results/species_common.csv'
        self.metadata_csv = '/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/genomes_2/metadata_genomes_2.csv' 
        self.master_output = '/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/genomes_2/busco_run_05_results/master_output'+str(self.number_of_orthologs)+'.csv'

    # this populates the self.node_relationship dictionary with node-to-parent that I outlined by hand. This allows me to calculate divergence between nodes later on
    def populate_relationships(self):
      with open(self.node_details, 'r') as node_details:
         node_details = pd.read_csv(node_details)
         for column in node_details:
            self.node_relationship[column]={}
            for node in node_details[column]:
               if pd.isna(node):
                  pass
               else:
                  self.node_relationship[column][node]=[]

    # this populates the self.node_gc_dict with information from the .lk and GC .tree files
    def populate_gc(self):
        os.chdir(self.output_path)
        # everytime this is run the self.node_gc_dict = {} needs to be reset # this shoudn't be problem since the nodes should be named the same
        # self.node_counter absolutely needs to be reset
        self.node_counter = 44
        for filename in self.newick_list:
           if self.ortholog+self.end_ij == filename:
              with open(filename, 'r') as tree:
                  tree = tree.readline()
              self.node_gc_dict = {}
              pattern = re.compile(r'([^\(\):,\s]+).(\d+\.\d+):')  # Pattern to find name, distance
              matches = pattern.finditer(tree)
              for match in matches:
                  match_string = match.group()
                  node = match.group(1)
                  gc = match.group(2)
                  # If there's a space six positions before the colon, this is a taxon tip
                  if ' ' in match_string:
                      if node not in self.node_gc3_total.keys():
                         self.node_gc3_total[node] = [float(gc)]
                         #self.node_gc3_total[node] = [[float(gc),self.ortholog]]
                      else:
                         self.node_gc3_total[node].append(float(gc))
                         #self.node_gc3_total[node].append([float(gc),self.ortholog])
                      #print(node,gc)
                      self.node_gc_dict[node] = float(gc)
                      #pass
                  # If the sixth position is a closing parenthesis ')', this is a node
                  elif ')' in match_string:
                      node = f'node_{self.node_counter}'
                      if node not in self.node_gc3_total.keys():
                         self.node_gc3_total[node] = [float(gc)]
                      else:
                         self.node_gc3_total[node].append(float(gc))
                      #print(node,gc)
                      self.node_counter += 1
                  # Add to dictionary
                      self.node_gc_dict[node] = float(gc)
        # this grabs the ancestral gc content for gene k
        for filename in self.ancestral_list:
           if self.ortholog+self.end_ancestral == filename:
               with open(filename, 'r') as output:
                  output=output.readlines()
                  if 'Ancestral' in output[1]:
                      ancestral = output[1][16:]
                      self.node_gc_dict['ancestral']=float(ancestral.rstrip())*100
                      if 'ancestral' not in self.node_gc3_total.keys():
                         self.node_gc3_total['ancestral']=[float(ancestral.rstrip())*100]
                      else:
                         self.node_gc3_total['ancestral'].append(float(ancestral.rstrip())*100)
        #print(len(self.node_gc3_total['ancestral']))
        #print(len(self.node_gc_dict))


    # this makes a list for each species where each number = (GC3i,k-GC3j,k)**2
    def calculate_dij(self):
      # node_ri is the daughter, node_rj is the ancestral
      for node_ri in self.node_relationship.keys():
         for node_rj in self.node_relationship[node_ri].keys():
            for node in self.node_gc_dict.keys():
               if node == node_rj:
                  self.node_relationship[node_ri][node_rj].append(((float(self.node_gc_dict[node_ri])-float(self.node_gc_dict[node_rj]))**2))
      #print(self.node_relationship)

    # this makes a list for each species where each number = (GC3i,k-GC3anc,k)**2
    def calculate_dianc(self):
      for species in self.node_relationship.keys():
         if 'node' not in species:
            if species not in self.node_anc_relationship.keys():
               self.node_anc_relationship[species]=[]
               self.node_anc_relationship[species].append(((self.node_gc_dict[species]-self.node_gc_dict['ancestral'])**2))
            else:
               self.node_anc_relationship[species].append(((self.node_gc_dict[species]-self.node_gc_dict['ancestral'])**2))


    #this will make sure I am running the same ortholog through both methods at the same time
    def N_sync(self):
      #print(len(self.ortholog_list)) # this should be 2631
      for o in self.ortholog_list:
         #self.ortholog is a global? variable that will be changed each time I iterate through the ortholog list
         #if o == '85255at8457': # this was used for troubleshooting
         self.ortholog = o
         print('calculating',self.ortholog)
         self.populate_gc()
         self.calculate_dij()
         self.calculate_dianc()

    def dij(self):
      for node, parent_dict in self.node_relationship.items():
         for parent, dist_list in parent_dict.items():
            result = math.sqrt(sum(dist_list))
            self.dij_dict[node]={}
            self.dij_dict[node][parent]=result
      return(self.dij_dict)

    def dianc(self):
      for species in self.node_anc_relationship.keys():
         result = math.sqrt(sum(self.node_anc_relationship[species]))
         self.dianc_dict[species]=result
      return(self.dianc_dict)

    def export_dij(self):
      json_object = json.dumps(self.dij_dict, indent=4, ensure_ascii=False)
      with open(self.dij_output, 'w', encoding='utf-8') as f:
         f.write(json_object)

    def export_dianc(self):
      json_object = json.dumps(self.dianc_dict, indent=4, ensure_ascii=False)
      with open(self.dianc_output, 'w', encoding='utf-8') as f:
         f.write(json_object)

    def make_gc3_per_gene_dir(self):
      os.chdir(self.top)
      file_list = os.listdir(self.top)
      name = '03_gc3_per_gene'
      if name in file_list:
         pass
      elif name not in file_list:
         command = subprocess.run(['mkdir', f'{name}'])

    #def export_gc3(self): # this method needs to be edited depending on the type of GC3 data I want
      #os.chdir(self.dir_gc3_per_gene) # this line should be uncommented if I want gene specific information
      #for species in self.node_gc3_total:
         #if type(self.node_gc3_total[species][0]) == list:  # this line should be uncommented if I want gene specific information
            #data = pd.DataFrame(self.node_gc3_total[species])  # this line should be uncommented if I want gene specific information
            #data.to_csv(species+'_gc3_per_gene.csv', index = False)  # this line should be uncommented if I want gene specific information
         #self.node_gc3_total[species] = sum(self.node_gc3_total[species])/len(self.node_gc3_total[species])
      #json_object = json.dumps(self.node_gc3_total, indent=4, ensure_ascii=False)
      #with open(self.gc3_output, 'w', encoding='utf-8') as f:
         #f.write(json_object)

    def export_gc3_vs_stdv(self):
       species_gc3_stdv_dict = {}
       for species in self.node_gc3_total:
         if 'node' not in species:
            species_gc3_stdv_dict[species] = [sum(self.node_gc3_total[species])/len(self.node_gc3_total[species]),statistics.stdev(self.node_gc3_total[species])]
       data = pd.DataFrame(species_gc3_stdv_dict)
       data.to_csv(self.gc3_vs_stdv_output, index = False)

    def export_master(self): # this needs to be edited so that the rows have headers in the output
       dicts_list = []
       species_gc3_dict = {}
       species_stdv_dict = {}
       genome_size_dict = {}
       species_mass_dict = {}
       species_common_dict = {}
       species_accession_dict = {}
       for species in self.node_gc3_total:
         if 'node' not in species and 'ances' not in species:
            species_gc3_dict[species] = sum(self.node_gc3_total[species])/len(self.node_gc3_total[species])
            species_stdv_dict[species] = statistics.stdev(self.node_gc3_total[species])
       for species in self.node_anc_relationship.keys():
         result = math.sqrt(sum(self.node_anc_relationship[species]))
         self.dianc_dict[species]=result
       genome_size_df = pd.read_csv(self.genome_size_csv)
       for species in self.node_anc_relationship.keys():
          for i in range(len(genome_size_df['organism_name'])):
             if species == genome_size_df['organism_name'][i]:
                genome_size_dict[species] = genome_size_df['end'][i]
       species_mass_df = pd.read_csv(self.species_mass_csv)
       for i in range(len(species_mass_df['genus_species'])):
          species_mass_dict[species_mass_df['genus_species'][i]] = species_mass_df['mass'][i]
       species_common_df = pd.read_csv(self.species_common_csv)
       for i in range(len(species_common_df['genus_species'])):
          species_common_dict[species_common_df['genus_species'][i]] = species_common_df['common_name'][i]
       metadata_df = pd.read_csv(self.metadata_csv)
       for i in range(len(metadata_df['organismName'])):
          if metadata_df['organismName'][i] in species_gc3_dict:
             species_accession_dict[metadata_df['organismName'][i]] = metadata_df['accession'][i]
       dicts_list.append(species_gc3_dict)
       dicts_list.append(species_stdv_dict)
       dicts_list.append(self.dianc_dict)
       dicts_list.append(genome_size_dict)
       dicts_list.append(species_mass_dict)
       dicts_list.append(species_common_dict)
       dicts_list.append(species_accession_dict)
       data = pd.DataFrame.from_dict(dicts_list)
#       print(data)
#       #data = pd.DataFrame(species_gc3_stdv_dict)
       data.to_csv(self.master_output, index = False)

    # troubleshooting
    def print_lists(self):
      #print(len(self.newick_list))
      #print(len(self.ancestral_list))
      #print(len(self.ortholog_list))
      for node in self.node_gc3_total:
         print(node)
         print(len(self.node_gc3_total[node]))
      #for node in self.dij_dict:
      #   print(node)
      #   print(self.dij_dict[node])
      #for node in self.dianc_dict:
      #   print(node)
      #   print(self.dianc_dict[node])
      #for node in self.node_gc_dict:
      #  print(node)
      #  print(self.node_gc_dict[node])

    def example_tree(self):
        os.chdir(self.output_path)
        # everytime this is run the self.node_gc_dict = {} needs to be reset # this shoudn't be problem since the nodes should be named the same
        # self.node_counter absolutely needs to be reset
        self.node_counter = 44
        with open('/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/genomes_2/busco_run_05_results/02_consolidate_copy/02_with_names/13at8457.phylip_nhPhymlGC.tree', 'r') as tree:
         tree = tree.readline()
        self.node_gc_dict = {}
        pattern = re.compile(r'([^\(\):,\s]+).(\d+\.\d+):')  # Pattern to find name, distance
        matches = pattern.finditer(tree)
        for match in matches:
          match_string = match.group()
          node = match.group(1)
          gc = match.group(2)
          # If there's a space six positions before the colon
          if ' ' in match_string:
              #if node not in self.node_gc3_total.keys():
              #   self.node_gc3_total[node] = [float(gc)]
              #else:
              #   self.node_gc3_total[node].append(float(gc))
              #print(node,gc)
              self.node_gc_dict[node] = float(gc)
              #pass
          # If the sixth position is a closing parenthesis ')'
          elif ')' in match_string:
              node = f'node_{self.node_counter}'
              #if node not in self.node_gc3_total.keys():
              #   self.node_gc3_total[node] = [float(gc)]
              #else:
              #   self.node_gc3_total[node].append(float(gc))
              #print(node,gc)
              self.node_counter += 1
           # Add to dictionary
              self.node_gc_dict[node] = float(gc)
        # this grabs the ancestral gc content for gene k
        with open('/media/lepidodactylus/2aa24196-95e9-4ebf-8899-7161cb272356/home/leptodactylus/genomes_2/busco_run_05_results/02_consolidate_copy/02_with_names/13at8457.phylip_nhPhyml.lk', 'r') as output:
          output=output.readlines()
          if 'Ancestral' in output[1]:
              ancestral = output[1][16:]
              self.node_gc_dict['ancestral']=float(ancestral.rstrip())*100


# Usage
parser = TreeParser() # initiate the class?
parser.populate_relationships() # uses csv to establish relationships
parser.N_sync() # this fills the self.node_relationship and self.node_anc_relationship dictionaries
#parser.dij() # this sums all squared differences and finds the squaroot of the result
#parser.dianc() # this sums all squared differences and finds the squaroot of the result
#parser.export_dij() # exports to json
#parser.export_dianc() # exports to json
#parser.make_gc3_per_gene_dir()
#parser.export_gc3()
#parser.export_gc3_vs_stdv()
parser.export_master()
#parser.example_tree()
#parser.print_lists()
